# Generated by Django 4.2.11 on 2026-04-03 11:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Encargado de Sucursal'), ('vendor', 'Vendedor')], default='vendor', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Sucursal')),
                ('code', models.CharField(max_length=50, verbose_name='Código de Sucursal')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Marca')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_generic', models.BooleanField(default=False, verbose_name='Es Cliente Genérico')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document_type', models.CharField(choices=[('ci', 'Cédula de Identidad'), ('ruc', 'RUC'), ('passport', 'Pasaporte')], default='ci', max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Empresa')),
                ('ruc', models.CharField(max_length=50, unique=True, verbose_name='RUC')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='Paraguay', max_length=100, verbose_name='País')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('subscription_status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20, verbose_name='Estado de Suscripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cotización (USD/PYG)')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fuente')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Forma de Pago')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_forms', to='core.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='models/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.brand', verbose_name='Marca')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='core.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo',
                'verbose_name_plural': 'Modelos de Vehículos',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='VIN')),
                ('license_plate', models.CharField(blank=True, max_length=50, verbose_name='Placa de Patente')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('mileage', models.IntegerField(default=0, verbose_name='Kilometraje')),
                ('fob', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FOB (Costo Base)')),
                ('container', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CONTEN (Costo Contenedor)')),
                ('dispatch', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='DESPACHO')),
                ('cam_vol', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CAM/VOL (Carga/Volumen)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('currency', models.CharField(choices=[('PYG', 'Guaraní'), ('USD', 'Dólar')], default='PYG', max_length=10, verbose_name='Moneda')),
                ('state', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('maintenance', 'Mantenimiento')], default='available', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.branch', verbose_name='Sucursal')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand', verbose_name='Marca')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.enterprise', verbose_name='Empresa')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exchangerate', verbose_name='Cotización')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiclemodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Venta')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Sucursal')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.customer', verbose_name='Cliente')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.enterprise', verbose_name='Empresa')),
                ('payment_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentform', verbose_name='Forma de Pago')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Quotum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_number', models.IntegerField(verbose_name='Número de Cuota')),
                ('plan_name', models.CharField(blank=True, max_length=100, verbose_name='Plan de Financiación')),
                ('total_plan', models.IntegerField(verbose_name='Total de Cuotas del Plan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de Cuota')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interés')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Cobrada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas', to='core.customer', verbose_name='Cliente')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='core.enterprise', verbose_name='Empresa')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='core.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['sale', 'quota_number'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.enterprise', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='brand',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.enterprise', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.enterprise', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_managed', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('view', 'Ver'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('export', 'Exportar'), ('import', 'Importar')], max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('object_id', models.IntegerField(verbose_name='ID del Objeto')),
                ('object_str', models.CharField(max_length=255, verbose_name='Objeto')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Valores Nuevos')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.enterprise', verbose_name='Empresa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.enterprise', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['enterprise', 'brand'], name='core_vehicl_enterpr_c2d380_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['is_active'], name='core_vehicl_is_acti_5c31a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together={('enterprise', 'brand', 'name')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['enterprise', 'branch', 'state'], name='core_vehicl_enterpr_40fc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='core_vehicl_vin_167573_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['state'], name='core_vehicl_state_7ff3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['enterprise', 'branch', 'sale_date'], name='core_sale_enterpr_d23449_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_number'], name='core_sale_sale_nu_5e4ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='core_sale_status_c7c270_idx'),
        ),
        migrations.AddIndex(
            model_name='quotum',
            index=models.Index(fields=['enterprise', 'customer', 'due_date'], name='core_quotum_enterpr_80e9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='quotum',
            index=models.Index(fields=['status', 'due_date'], name='core_quotum_status_7628ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotum',
            unique_together={('sale', 'quota_number')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentform',
            unique_together={('enterprise', 'name')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['enterprise', 'is_active', 'date'], name='core_exchan_enterpr_ebecba_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['ruc'], name='core_enterp_ruc_37b1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['subscription_status'], name='core_enterp_subscri_493c21_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['enterprise', 'document_number'], name='core_custom_enterpr_68ce63_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['enterprise', 'is_generic'], name='core_custom_enterpr_c73d43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('enterprise', 'document_number')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['enterprise', 'is_active'], name='core_brand_enterpr_3462d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('enterprise', 'name')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['enterprise', 'code'], name='core_branch_enterpr_0949f1_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='core_branch_is_acti_582342_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('enterprise', 'code')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['enterprise', 'timestamp'], name='core_auditl_enterpr_32726a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
    ]
