# Generated by Django 4.2.11 on 2026-04-05 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('vehicles', 'Vehículos'), ('sales', 'Ventas'), ('quotas', 'Cuotas'), ('customers', 'Clientes'), ('customer_list_crm', 'CRM - Gestión de Clientes'), ('customer_edit', 'CRM - Editar Cliente'), ('sale_register', 'CRM - Registrar Venta'), ('quota_payment', 'CRM - Cobrar Cuota'), ('payment_history', 'CRM - Historial de Pagos')], max_length=50, verbose_name='Vista')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Permitido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Vista',
                'verbose_name_plural': 'Permisos de Vista',
                'ordering': ['user', 'view_name'],
                'unique_together': {('user', 'view_name')},
            },
        ),
    ]
