# Generated by Django 4.2.11 on 2026-05-15 07:59
"""Agrega Quotum.payment_method y migra los datos desde el workaround
previo donde la forma de cobro vivía como prefijo `[EF]`/`[TB]`/`[CJ]`/`[AC]`
dentro del campo `notes`.

Backfill (reversible):
  - busca cualquier Quotum cuya nota arranque con `[XX]` donde XX está en
    el set permitido; setea `payment_method=XX`.
  - LIMPIA el prefijo de la nota para evitar duplicación (la nota queda
    con el resto del texto; si no había más texto queda vacía).

Reverse:
  - vuelve a poner el prefijo `[XX]` al inicio de notes y borra
    payment_method, dejando los registros como estaban antes.
"""
import re
from django.db import migrations, models


VALID_METHODS = ('EF', 'TB', 'CJ', 'AC')
PATTERN = re.compile(r'^\s*\[(EF|TB|CJ|AC)\]\s*', re.IGNORECASE)


def backfill_payment_method_from_notes(apps, schema_editor):
    Quotum = apps.get_model('core', 'Quotum')
    updated = 0
    for q in Quotum.objects.exclude(notes='').exclude(notes__isnull=True).iterator(chunk_size=500):
        m = PATTERN.match(q.notes or '')
        if not m:
            continue
        method = m.group(1).upper()
        if method not in VALID_METHODS:
            continue
        q.payment_method = method
        # Limpiamos el prefijo `[XX]` y los espacios contiguos.
        q.notes = PATTERN.sub('', q.notes, count=1).strip()
        q.save(update_fields=['payment_method', 'notes'])
        updated += 1
    print(f'  backfill payment_method: {updated} cuota(s) actualizadas')


def restore_payment_method_to_notes(apps, schema_editor):
    """Reverse: vuelve a poner [XX] al inicio de notes y limpia payment_method."""
    Quotum = apps.get_model('core', 'Quotum')
    restored = 0
    for q in Quotum.objects.exclude(payment_method='').exclude(payment_method__isnull=True).iterator(chunk_size=500):
        prefix = f'[{q.payment_method}]'
        if q.notes:
            q.notes = f'{prefix} {q.notes}'
        else:
            q.notes = prefix
        q.payment_method = None
        q.save(update_fields=['payment_method', 'notes'])
        restored += 1
    print(f'  reverse: {restored} cuota(s) restauradas a notes')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_branches_visible'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehiclecost',
            new_name='core_vehicl_vehicle_24e37d_idx',
            old_name='core_vehicl_vehicle_idx',
        ),
        migrations.AddField(
            model_name='quotum',
            name='payment_method',
            field=models.CharField(
                blank=True, null=True, max_length=2,
                choices=[('EF', 'Efectivo'), ('TB', 'Transferencia bancaria'),
                         ('CJ', 'Caja'), ('AC', 'Acuerdo')],
                verbose_name='Forma de cobro',
            ),
        ),
        migrations.RunPython(
            backfill_payment_method_from_notes,
            reverse_code=restore_payment_method_to_notes,
        ),
    ]
