# Generated by Django 4.2.11 on 2026-05-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quotum_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('kind', models.CharField(choices=[('cobro_cuota', 'Cobro de cuota'), ('venta_contado', 'Venta contado'), ('seña_credito', 'Seña de crédito'), ('pago_a_cuenta', 'Pago a cuenta'), ('gasto_playa', 'Gasto playa'), ('alquiler', 'Alquiler'), ('sueldo', 'Sueldo'), ('comision', 'Comisión / honorario'), ('compra_exterior', 'Compra al exterior'), ('transporte', 'Transporte / despacho'), ('impuesto', 'Impuesto'), ('ajuste', 'Ajuste de caja'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('direction', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Egreso')], max_length=3, verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='Operación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('currency', models.CharField(choices=[('PYG', 'PYG'), ('USD', 'USD')], default='PYG', max_length=3, verbose_name='Moneda')),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en USD')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tipo de cambio')),
                ('provider', models.CharField(blank=True, help_text='Ej: AUTOWINI, DADANI, LAYSOLA — para compras al exterior', max_length=100, verbose_name='Proveedor')),
                ('is_auto', models.BooleanField(default=False, help_text='True cuando proviene de una venta o cobro de cuota; False cuando lo creó un usuario manualmente.', verbose_name='Generado automáticamente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='core.branch', verbose_name='Sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='core.enterprise', verbose_name='Empresa')),
                ('quota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='core.quotum', verbose_name='Cuota')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='core.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['enterprise', 'date'], name='core_cashmo_enterpr_e3dfe0_idx'), models.Index(fields=['enterprise', 'branch', 'date'], name='core_cashmo_enterpr_3aa61e_idx'), models.Index(fields=['kind'], name='core_cashmo_kind_29d9e0_idx'), models.Index(fields=['direction'], name='core_cashmo_directi_9268ef_idx'), models.Index(fields=['sale'], name='core_cashmo_sale_id_25e59d_idx'), models.Index(fields=['quota'], name='core_cashmo_quota_i_53fcf2_idx')],
            },
        ),
    ]
