# Generated by Django 5.1.4 on 2026-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vehiclecost_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Reserva'), ('completed', 'Cerrada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
