# Generated by Django 6.1 on 2026-08-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vehicle_search_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Cobro / Entrega'),
        ),
    ]
