# Generated by Django 6.1 on 2026-08-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sale_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador URL-friendly usado en /catalogo/{slug}/', max_length=100, null=True, unique=True, verbose_name='Slug URL público'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='Foto')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subida')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Foto de vehículo',
                'verbose_name_plural': 'Fotos de vehículos',
                'ordering': ['vehicle_id', 'order', 'id'],
                'indexes': [models.Index(fields=['vehicle'], name='core_vehicl_vehicle_fedbe8_idx')],
            },
        ),
    ]
