# Generated by Django 6.1 on 2026-08-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_enterprise_slug_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecost',
            name='date',
            field=models.DateField(blank=True, help_text='Cuándo se realizó el trabajo o se pagó el gasto.', null=True, verbose_name='Fecha del gasto'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehiclecost',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Quién realizó el trabajo (mecánico, chapista, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='core.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['enterprise', 'is_active'], name='core_suppli_enterpr_fd8adb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('enterprise', 'name')},
        ),
    ]
