# Generated by Django 5.1.4 on 2026-05-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Trial 14 días'), ('starter', 'Starter'), ('pro', 'Profesional'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='Plan')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida (impago)'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del trial')),
                ('current_period_ends_at', models.DateTimeField(blank=True, help_text='Mensual o anual según el plan. Si pasa esta fecha sin renovación, la suscripción se considera expirada.', null=True, verbose_name='Fin del período actual')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('external_customer_id', models.CharField(blank=True, max_length=100)),
                ('external_subscription_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enterprise_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(blank=True, help_text='Una vez confirmado, apunta a la enterprise creada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enterprise')),
            ],
            options={
                'verbose_name': 'Solicitud de signup',
                'verbose_name_plural': 'Solicitudes de signup',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='saas_signup_token_76f825_idx'), models.Index(fields=['email'], name='saas_signup_email_2df7c8_idx')],
            },
        ),
    ]
